### ISSUE TITLE
BuiltIn Type highlight in Visual Studio not working

### ISSUE THREAD

**Issue by Simulacrux** [zeroc-ice/vscode-slice#2]
Hi, 

I'm not sure if this is an issue on your side, or if I'm doing something wrong.
I tried to install your syntax highlight in Visual Studio and it works pretty good. 

Unfortunately the BuiltIn types are not highlighted. Everything else works just fine, even the optional(1) or out features are correctly highlighted. The Build in type highlight is also not working in an interface function as parameter or return value.

![ice_syntax_01](https://user-images.githubusercontent.com/12858171/46852840-9597b400-cdfc-11e8-886b-0af89c570bd5.png)

Is this a bug in VS or a glitch in your grammar?

Thank you for your time and effort to make this TextMate Grammar

Cheers Simulacrux

**Comment by InsertCreativityHere** [comment]
The highlighting works fine for me using it with VS2017, my guess would be either that it's a bug in VS, or maybe the color theme you're using just doesn't highlight it.

What Visual Studio version and color theme are you using? If it's just the theme, then I can add support to properly highlight builtins for it.

**Comment by Simulacrux** [comment]
I'm using a Visual Studio 2015 Enterprise with the "Blue" color theme.
If I could give you more information on a special "Type" in the Font and Color section, please let me know.

**Comment by InsertCreativityHere** [comment]
Looks like this is just a bug in VS2015, it doesn't parse the grammar file correctly. I might be able to rewrite it in a way that VS2015 will parse, but it seems to work fine in VS2017, and all the versions of VSCode I could try it with.

**Comment by Simulacrux** [comment]
No need to bother, if it is only a glitch in our old version. We plan to update to VS2017 in the next couple of weeks, so we will stick with it for the time. The files are much more highlighted, so it is a huge plus in comfort right now. 

Thank you for your testing.

**Comment by InsertCreativityHere** [comment]
Yeah sure, good luck with the update!
