### ISSUE TITLE
syntax highlight Not working in VS CODE 

### ISSUE THREAD

**Issue by CHITTIMOTU** [zeroc-ice/vscode-slice#3]
Not working in VS CODE 
able to install extension, but no syntax highlight in .slice file
![image](https://user-images.githubusercontent.com/65209890/192129743-2091cd24-3106-4960-9895-255d466ba32d.png)

**Comment by InsertCreativityHere** [comment]
I'm going to close this for now since we never heard back.
If there's something else going on and you're still having issues, feel free to re-open this with more details!
