### ISSUE TITLE
README in version 4.4.0

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/vscode-slice#45]
A few issues with the latest README:

- it would be helpful to mention where the settings file is (.vscode/settings.json)
- "Each configuration..." and its sublist should not be on the same level
- IceRPC is not spelled according to our branding guidelines
- addWellKnownTypes:
   - we need to document the default value
   - the WellKnownTypes are Slice well-known types and are RPC independent
   - but in practice "addWellKnownTypes" is about the Slice well-known types and many additional Slice types of lesser importance like IceRpc::ServiceAddress and IceRpc::StatusCode.
   - nevertheless the link goes to the WellKnownTypes folder

Maybe we should provide two variables:
 - addWellKnownTypes (or includeWellKnownTypes?) for the Slice well-known types
 - addIceRpcTypes/Definitions (or include...) for the IceRPC types/definitions

See:
https://nuget.info/packages/ZeroC.Slice/0.2.1 ( = Slice well-known types)
https://nuget.info/packages/IceRpc/0.2.1 (= IceRPC Slice files)
https://nuget.info/packages/IceRpc.Slice/0.2.1 (= additional Slice files provided by the IceRPC + Slice integration)

**Comment by InsertCreativityHere** [comment]
The README was improved in #58.
