### ISSUE TITLE
Avoid Reporting Errors for Built-in Slice Files?

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/vscode-slice#49]
While testing in `icerpc-slice`, I set `include-built-in-slice-files` to `true`.
This of course caused redefinition errors everywhere (since those built in files _are_ `icerpc-slice`), which is what I expected.
But... not every file was marked as a redefinition. And every time I opened a file, the erroneous files changes randomly.

What's happening is that half the redefinition errors are reported for the users Slice file,
and half are reported for the files we bundle with the extension.

Is there any point to publishing errors for the bundled files? Or should we just filter these errors out when going to report?
Assuming that we haven't screwed everything up (which I think is a safe assumption).

**Comment by ReeceHumphreys** [comment]
It seems that the root issue lies in the inconsistent order in which files are passed to the slice compiler. This leads to redefinitions being written in the bundled files if they're processed first, or in the user's files if those are prioritized. Ideally, we should only report definition errors in the user's slice files. 

We should never be pushing diagnostics to the bundled files as that's just pointless.
