### ISSUE TITLE
Rename Extension to "Slice"

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/vscode-slice#7]
Currently, it's named "Slice Highlighter", but once we start adding additional functionality to it, we should rename it to just "Slice".

**Note**: there is already an extension named "Slice", but it's okay for 2 extensions to use the same display name (as far as I can tell).

**Comment by ReeceHumphreys** [comment]
I think we should just go ahead and rename it to slice now. Its a simpler name which is better - no reason to hold off on doing it since it is a simple channge.
